name: 'Generate PHP doc'
on:
  pull_request:
    branches:
      - master
jobs:
  master:
    name: 'build'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Run docs
        run: cd shell/ci && ./phpdoc.sh


